USE [master]
GO

/****** Object:  Database [TMDB]    Script Date: 6/13/2018 12:28:46 PM ******/
CREATE DATABASE [TMDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TMDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TMDB.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TMDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TMDB_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TMDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TMDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TMDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TMDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TMDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TMDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TMDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TMDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TMDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TMDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TMDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TMDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TMDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TMDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TMDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TMDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TMDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TMDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TMDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TMDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TMDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TMDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TMDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TMDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TMDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TMDB] SET  MULTI_USER 
GO

ALTER DATABASE [TMDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TMDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TMDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TMDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TMDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TMDB] SET  READ_WRITE 
GO


